In [1]:
import nltk
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()

In [2]:
example="A cat was chasing a mouse"
example=[stemmer.stem(token) for token in example.split(" ")]
print(" ".join(example))

A cat wa chase a mous


In [3]:
example=""""Sophie Karthäuser (born May 1974) is a Belgian operatic soprano. She has performed internationally, especially in roles by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist, performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."""
example=[stemmer.stem(token) for token in example.split(" ")]
print(" ".join(example))

"sophi karthäus (born may 1974) is a belgian operat soprano. she ha perform internationally, especi in role by mozart such as ilia in idomeneo and pamina in the magic flute. she is also a recitalist, perform and record for exampl the complet song by mozart and lieder by hugo wolf.


In [4]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
example="A cat was chasing a mouse"
example=[lemmatizer.lemmatize(token) for token in example.split(" ")]
print(" ".join(example))

A cat wa chasing a mouse


In [5]:
print(lemmatizer.lemmatize('better', pos='a'))
print(lemmatizer.lemmatize('better'))

good
better


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
vect=CountVectorizer(binary= True)
corpus=["Sophie lovozar (born May 1974) is a Belgian operatic", "soprano. She has performed internationally, especially in roles", "by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist,"," performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]
vect.fit(corpus)
print(vect.transform)
print(vect.transform(["Sophie Karthäuser (born May 1974) is a Belgian operatic soprano. She has performed internationally, especially in roles by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist, performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]))


<bound method CountVectorizer.transform of CountVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)>
  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1
  (0, 8)	1
  (0, 9)	1
  (0, 10)	1
  (0, 11)	1
  (0, 12)	1
  (0, 13)	1
  (0, 14)	1
  (0, 15)	1
  (0, 16)	1
  (0, 17)	1
  (0, 18)	1
  (0, 19)	1
  (0, 20)	1
  (0, 21)	1
  (0, 22)	1
  (0, 23)	1
  (0, 24)	1
  (0, 25)	1
  (0, 26)	1
  (0, 27)	1
  (0, 28)	1
  (0, 29)	1
  (0, 30)	1
  (0, 31)	1
  (0, 32)	1
  (0, 33)	1
  (0, 34)	1
  (0, 35)	1
  (0, 36)	1
  (0, 37)	1


In [8]:
vect=CountVectorizer(binary= True)
corpus=["Sophie lovozar (born May 1974) is a Belgian operatic", "soprano. She has performed internationally, especially in roles", "by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist,"," performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]
vect.fit(corpus)
print(vect.transform)
print(vect.transform(["Sophie Karthäuser (born May 1974) is a Belgian operatic soprano. She has performed internationally, especially in roles by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist, performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]))


<bound method CountVectorizer.transform of CountVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)>
  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1
  (0, 8)	1
  (0, 9)	1
  (0, 10)	1
  (0, 11)	1
  (0, 12)	1
  (0, 13)	1
  (0, 14)	1
  (0, 15)	1
  (0, 16)	1
  (0, 17)	1
  (0, 18)	1
  (0, 19)	1
  (0, 21)	1
  (0, 22)	1
  (0, 23)	1
  (0, 24)	1
  (0, 25)	1
  (0, 26)	1
  (0, 27)	1
  (0, 28)	1
  (0, 29)	1
  (0, 30)	1
  (0, 31)	1
  (0, 32)	1
  (0, 33)	1
  (0, 34)	1
  (0, 35)	1
  (0, 36)	1
  (0, 37)	1


In [9]:
vect=CountVectorizer(binary= True)
corpus=["Sophie lovozar (born May 1974) is a Belgian operatic", "soprano. She has performed internationally, especially in roles", "by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist,"," performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]
vect.fit(corpus)
print(vect.transform)
print(vect.transform(["Sophie TL (born May 1974) is a Belgian operatic soprano. She has performed internationally, especially in roles by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist, performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]).toarray())


<bound method CountVectorizer.transform of CountVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)>
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1]]


In [10]:
vect=CountVectorizer(binary= True)
corpus=["Sophie lovozar (born May 1974) is a Belgian operatic", "soprano. She has performed internationally, especially in roles", "by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist,"," performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]
vect.fit(corpus)
print(vect.transform)
print(vect.transform(["Sophie TL (born May 1974) is a Belgian operatic soprano. She has performed internationally, especially in roles by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist, performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]).toarray())


<bound method CountVectorizer.transform of CountVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)>
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1]]


In [11]:
vect=TfidfVectorizer(binary= False)
corpus=["Sophie lovozar (born May 1974) is a Belgian operatic", "soprano. She has performed internationally, especially in roles", "by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist,"," performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]
vect.fit(corpus)
print(vect.transform)
print(vect.transform(["Sophie TL (born May 1974) is a Belgian operatic soprano. She has performed internationally, especially in roles by Mozart such as Ilia in Idomeneo and Pamina in The Magic Flute. She is also a recitalist, performing and recording for example the complete songs by Mozart and lieder by Hugo Wolf."]).toarray())


<bound method TfidfVectorizer.transform of TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)>
[[0.13276983 0.13276983 0.31403178 0.13276983 0.13276983 0.13276983
  0.31403178 0.13276983 0.13276983 0.13276983 0.13276983 0.13276983
  0.13276983 0.13276983 0.13276983 0.13276983 0.31403178 0.13276983
  0.20935452 0.13276983 0.         0.13276983 0.13276983 0.20935452
  0.13276983 0.13276983 0.13276983 0.13276983 0.13276983 0.13276983
  0.13276983 0.20935452 0.13276983 0.13276983 0.13276983 0.13276983
  0.20935452 0.13276983]]


In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer()

SyntaxError: invalid syntax (<ipython-input-12-270030f014f8>, line 1)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
import pandas as pd

In [10]:
import numpy as np

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
vect=TfidfVectorizer(binary=False)

In [16]:
similarity=vect.transform(["""One of the finer books i read this uear was John kaag's Hiking With Nietzsche, in which Kaag, a professor of philosophy, rekindles his passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. It's a near-precise rendering of the travelogue as a self-help book. A young Kaag was an avowed Nietzsche acolyte but given the ravages of responsibilities and adulthood, the writer put his affinity to test by undertaking physically enduring hikes through the Alps, revisiting haunts that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own innre turmoil, are catnip for anybody feeling at cross purposes with their own life."""].toarray(),vect.transform(["""Summer is a charming flirt. Easy going and casual. Summer doesnt huff and puff to win our affection. It has us at "Hello". Winter broods like the tortured protagonist of big fat russian novel. It is daunting and dramatic, burning with a slow intensity.
The seasons reputation precedes itself, and often, not in a good way. It has a way of whittling down everything to its bare bones. Even relationships not attuned to its ebbs and flows can fray. At a dinner conversation I once attended, I listened in bemusement as a recent divorcee, made the case that it was the Scandinavian frost that had cooled his exwifes ardour. How original"""].toarray()))

AttributeError: 'list' object has no attribute 'toarray'

In [17]:
corpus=["""Summer is a charming flirt. Easy going and casual. Summer doesnt huff and puff to win our affection. It has us at "Hello". Winter broods like the tortured protagonist of big fat russian novel. It is daunting and dramatic, burning with a slow intensity.
The seasons reputation precedes itself, and often, not in a good way. It has a way of whittling down everything to its bare bones. Even relationships not attuned to its ebbs and flows can fray. At a dinner conversation I once attended, I listened in bemusement as a recent divorcee, made the case that it was the Scandinavian frost that had cooled his exwifes ardour. How original"""]

In [18]:
vect.fit(corpus)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [19]:
str1="Summer is a charming flirt. Easy going and casual. Summer doesnt huff and puff to win our affection. It has us at "Hello". Winter broods like the tortured protagonist of big fat russian novel. It is daunting and dramatic, burning with a slow intensity. The seasons reputation precedes itself, and often, not in a good way. It has a way of whittling down everything to its bare bones. Even relationships not attuned to its ebbs and flows can fray. At a dinner conversation I once attended, I listened in bemusement as a recent divorcee, made the case that it was the Scandinavian frost that had cooled his exwifes ardour. How original"

SyntaxError: invalid syntax (<ipython-input-19-f1675de6e488>, line 1)

In [20]:
str1="""Summer is a charming flirt. Easy going and casual. Summer doesnt huff and puff to win our affection. It has us at "Hello". Winter broods like the tortured protagonist of big fat russian novel. It is daunting and dramatic, burning with a slow intensity.
The seasons reputation precedes itself, and often, not in a good way. It has a way of whittling down everything to its bare bones. Even relationships not attuned to its ebbs and flows can fray. At a dinner conversation I once attended, I listened in bemusement as a recent divorcee, made the case that it was the Scandinavian frost that had cooled his exwifes ardour. How original"""

In [21]:
str2="""One of the finer books i read this uear was John kaag's Hiking With Nietzsche, in which Kaag, a professor of philosophy, rekindles his passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. It's a near-precise rendering of the travelogue as a self-help book. A young Kaag was an avowed Nietzsche acolyte but given the ravages of responsibilities and adulthood, the writer put his affinity to test by undertaking physically enduring hikes through the Alps, revisiting haunts that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own innre turmoil, are catnip for anybody feeling at cross purposes with their own life."""

In [29]:
vect=TfidfVectorizer(binary=True)

In [30]:
corpus=[str1,str2]

In [24]:
vectstr1=vect.transform([str1]).toarray()
vectstr2=vect.transform([str1]).toarray()


NotFittedError: TfidfVectorizer - Vocabulary wasn't fitted.

In [31]:
vect.fit(corpus)

TfidfVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [32]:
vectstr1=vect.transform([str1]).toarray()
vectstr2=vect.transform([str1]).toarray()

In [33]:
sim=cosine_similarity(vectstr1,vectstr2)

In [34]:
sim

array([[1.]])

In [35]:
vect=TfidfVectorizer(binary=True)

In [36]:
corpus=[str1,str2]

In [37]:
vect.fit(corpus)

TfidfVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [38]:
vectstr1=vect.transform([str1]).toarray()
vectstr2=vect.transform([str1]).toarray()

In [39]:
sim=cosine_similarity(vectstr1,vectstr2)

In [40]:
sim


array([[1.]])

In [41]:
vectstr1

array([[0.        , 0.        , 0.11541242, 0.        , 0.        ,
        0.        , 0.08211689, 0.        , 0.11541242, 0.        ,
        0.08211689, 0.08211689, 0.11541242, 0.11541242, 0.        ,
        0.11541242, 0.11541242, 0.11541242, 0.11541242, 0.        ,
        0.        , 0.11541242, 0.11541242, 0.        , 0.        ,
        0.11541242, 0.11541242, 0.11541242, 0.        , 0.11541242,
        0.11541242, 0.11541242, 0.        , 0.        , 0.11541242,
        0.        , 0.11541242, 0.11541242, 0.11541242, 0.11541242,
        0.11541242, 0.11541242, 0.11541242, 0.        , 0.        ,
        0.11541242, 0.11541242, 0.11541242, 0.11541242, 0.        ,
        0.        , 0.11541242, 0.11541242, 0.        , 0.11541242,
        0.11541242, 0.        , 0.        , 0.11541242, 0.11541242,
        0.11541242, 0.11541242, 0.        , 0.11541242, 0.        ,
        0.        , 0.        , 0.08211689, 0.11541242, 0.11541242,
        0.08211689, 0.        , 0.11541242, 0.11

In [42]:
vectstr2

array([[0.        , 0.        , 0.11541242, 0.        , 0.        ,
        0.        , 0.08211689, 0.        , 0.11541242, 0.        ,
        0.08211689, 0.08211689, 0.11541242, 0.11541242, 0.        ,
        0.11541242, 0.11541242, 0.11541242, 0.11541242, 0.        ,
        0.        , 0.11541242, 0.11541242, 0.        , 0.        ,
        0.11541242, 0.11541242, 0.11541242, 0.        , 0.11541242,
        0.11541242, 0.11541242, 0.        , 0.        , 0.11541242,
        0.        , 0.11541242, 0.11541242, 0.11541242, 0.11541242,
        0.11541242, 0.11541242, 0.11541242, 0.        , 0.        ,
        0.11541242, 0.11541242, 0.11541242, 0.11541242, 0.        ,
        0.        , 0.11541242, 0.11541242, 0.        , 0.11541242,
        0.11541242, 0.        , 0.        , 0.11541242, 0.11541242,
        0.11541242, 0.11541242, 0.        , 0.11541242, 0.        ,
        0.        , 0.        , 0.08211689, 0.11541242, 0.11541242,
        0.08211689, 0.        , 0.11541242, 0.11